-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: rustfmt
        name: Run rustfmt over rust files
        entry: rustup run nightly rustfmt
        language: system
        files: \.rs$
